CREATE TABLE account(
   user_id SERIAL PRIMARY KEY, --SERIAL: creates a sequence object and set the next value generated by the sequence
   username VARCHAR(50) UNIQUE NOT NULL,
	password VARCHAR(50) NOT NULL,
	email VARCHAR(260) NOT NULL,
	created_on TIMESTAMP NOT NULL,
	last_login TIMESTAMP
)
